server:
  port: 8082
  context-path: /recom
spring:
  datasource1:
    username: root
    password: cs.swust
    url: jdbc:mysql://localhost:3306/iteach_cernet1?useUnicode\=true&characterEncoding\=utf-8
    driver-class-name: com.mysql.jdbc.Driver

  datasource2:
      username: root
      password: cs.swust
      url: jdbc:mysql://localhost:3306/iteach_recom?useUnicode\=true&characterEncoding\=utf-8
      driver-class-name: com.mysql.jdbc.Driver