package com.recom.domain;

public class Attachment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Attachment.atta_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer attaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Attachment.atta_filename
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String attaFilename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Attachment.atta_location
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String attaLocation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Attachment.atta_size
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String attaSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Attachment.atta_downnum
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer attaDownnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Attachment.atta_source_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer attaSourceType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Attachment.atta_sourceid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer attaSourceid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Attachment.atta_ori_filename
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String attaOriFilename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Attachment.atta_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String attaDescribe;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Attachment.atta_id
	 * @return  the value of Attachment.atta_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getAttaId() {
		return attaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Attachment.atta_id
	 * @param attaId  the value for Attachment.atta_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setAttaId(Integer attaId) {
		this.attaId = attaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Attachment.atta_filename
	 * @return  the value of Attachment.atta_filename
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getAttaFilename() {
		return attaFilename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Attachment.atta_filename
	 * @param attaFilename  the value for Attachment.atta_filename
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setAttaFilename(String attaFilename) {
		this.attaFilename = attaFilename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Attachment.atta_location
	 * @return  the value of Attachment.atta_location
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getAttaLocation() {
		return attaLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Attachment.atta_location
	 * @param attaLocation  the value for Attachment.atta_location
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setAttaLocation(String attaLocation) {
		this.attaLocation = attaLocation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Attachment.atta_size
	 * @return  the value of Attachment.atta_size
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getAttaSize() {
		return attaSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Attachment.atta_size
	 * @param attaSize  the value for Attachment.atta_size
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setAttaSize(String attaSize) {
		this.attaSize = attaSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Attachment.atta_downnum
	 * @return  the value of Attachment.atta_downnum
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getAttaDownnum() {
		return attaDownnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Attachment.atta_downnum
	 * @param attaDownnum  the value for Attachment.atta_downnum
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setAttaDownnum(Integer attaDownnum) {
		this.attaDownnum = attaDownnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Attachment.atta_source_type
	 * @return  the value of Attachment.atta_source_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getAttaSourceType() {
		return attaSourceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Attachment.atta_source_type
	 * @param attaSourceType  the value for Attachment.atta_source_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setAttaSourceType(Integer attaSourceType) {
		this.attaSourceType = attaSourceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Attachment.atta_sourceid
	 * @return  the value of Attachment.atta_sourceid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getAttaSourceid() {
		return attaSourceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Attachment.atta_sourceid
	 * @param attaSourceid  the value for Attachment.atta_sourceid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setAttaSourceid(Integer attaSourceid) {
		this.attaSourceid = attaSourceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Attachment.atta_ori_filename
	 * @return  the value of Attachment.atta_ori_filename
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getAttaOriFilename() {
		return attaOriFilename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Attachment.atta_ori_filename
	 * @param attaOriFilename  the value for Attachment.atta_ori_filename
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setAttaOriFilename(String attaOriFilename) {
		this.attaOriFilename = attaOriFilename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Attachment.atta_describe
	 * @return  the value of Attachment.atta_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getAttaDescribe() {
		return attaDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Attachment.atta_describe
	 * @param attaDescribe  the value for Attachment.atta_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setAttaDescribe(String attaDescribe) {
		this.attaDescribe = attaDescribe;
	}
}