package com.recom.domain;

import java.util.Date;

public class BbsPost {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column BbsPost.bbpo_id
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    private Integer bbpoId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column BbsPost.bbpo_cour_id
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    private Integer bbpoCourId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column BbsPost.bbpo_user_id
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    private Integer bbpoUserId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column BbsPost.bbpo_title
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    private String bbpoTitle;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column BbsPost.bbpo_cont_len
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    private Integer bbpoContLen;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column BbsPost.bbpo_time
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    private Date bbpoTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column BbsPost.bbpo_updateTime
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    private Date bbpoUpdatetime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column BbsPost.bbpo_visitnum
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    private Integer bbpoVisitnum;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column BbsPost.bbpo_replynum
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    private Integer bbpoReplynum;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column BbsPost.bbpo_isbest
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    private Boolean bbpoIsbest;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column BbsPost.bbpo_istop
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    private Boolean bbpoIstop;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column BbsPost.bbpo_hasattach
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    private Boolean bbpoHasattach;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column BbsPost.bbpo_content
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    private String bbpoContent;
    
    /**
     * 发帖人姓名
     */
    private String bbpoUserName;

    /**
     * 发帖人所在部门id
     */
    private Integer bbpoUserDepartId;
    
    /**
     * 课程名称
     */
    private String bbpoCourName;
    
    
    public String getBbpoCourName() {
        return bbpoCourName;
    }

    public void setBbpoCourName(String bbpoCourName) {
        this.bbpoCourName = bbpoCourName;
    }

    public Integer getBbpoUserDepartId() {
        return bbpoUserDepartId;
    }

    public void setBbpoUserDepartId(Integer bbpoUserDepartId) {
        this.bbpoUserDepartId = bbpoUserDepartId;
    }

    public String getBbpoUserName() {
        return bbpoUserName;
    }

    public void setBbpoUserName(String bbpoUserName) {
        this.bbpoUserName = bbpoUserName;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column BbsPost.bbpo_id
     * @return  the value of BbsPost.bbpo_id
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public Integer getBbpoId() {
        return bbpoId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column BbsPost.bbpo_id
     * @param bbpoId  the value for BbsPost.bbpo_id
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public void setBbpoId(Integer bbpoId) {
        this.bbpoId = bbpoId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column BbsPost.bbpo_cour_id
     * @return  the value of BbsPost.bbpo_cour_id
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public Integer getBbpoCourId() {
        return bbpoCourId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column BbsPost.bbpo_cour_id
     * @param bbpoCourId  the value for BbsPost.bbpo_cour_id
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public void setBbpoCourId(Integer bbpoCourId) {
        this.bbpoCourId = bbpoCourId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column BbsPost.bbpo_user_id
     * @return  the value of BbsPost.bbpo_user_id
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public Integer getBbpoUserId() {
        return bbpoUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column BbsPost.bbpo_user_id
     * @param bbpoUserId  the value for BbsPost.bbpo_user_id
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public void setBbpoUserId(Integer bbpoUserId) {
        this.bbpoUserId = bbpoUserId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column BbsPost.bbpo_title
     * @return  the value of BbsPost.bbpo_title
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public String getBbpoTitle() {
        return bbpoTitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column BbsPost.bbpo_title
     * @param bbpoTitle  the value for BbsPost.bbpo_title
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public void setBbpoTitle(String bbpoTitle) {
        this.bbpoTitle = bbpoTitle;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column BbsPost.bbpo_cont_len
     * @return  the value of BbsPost.bbpo_cont_len
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public Integer getBbpoContLen() {
        return bbpoContLen;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column BbsPost.bbpo_cont_len
     * @param bbpoContLen  the value for BbsPost.bbpo_cont_len
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public void setBbpoContLen(Integer bbpoContLen) {
        this.bbpoContLen = bbpoContLen;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column BbsPost.bbpo_time
     * @return  the value of BbsPost.bbpo_time
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public Date getBbpoTime() {
        return bbpoTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column BbsPost.bbpo_time
     * @param bbpoTime  the value for BbsPost.bbpo_time
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public void setBbpoTime(Date bbpoTime) {
        this.bbpoTime = bbpoTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column BbsPost.bbpo_updateTime
     * @return  the value of BbsPost.bbpo_updateTime
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public Date getBbpoUpdatetime() {
        return bbpoUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column BbsPost.bbpo_updateTime
     * @param bbpoUpdatetime  the value for BbsPost.bbpo_updateTime
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public void setBbpoUpdatetime(Date bbpoUpdatetime) {
        this.bbpoUpdatetime = bbpoUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column BbsPost.bbpo_visitnum
     * @return  the value of BbsPost.bbpo_visitnum
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public Integer getBbpoVisitnum() {
        return bbpoVisitnum;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column BbsPost.bbpo_visitnum
     * @param bbpoVisitnum  the value for BbsPost.bbpo_visitnum
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public void setBbpoVisitnum(Integer bbpoVisitnum) {
        this.bbpoVisitnum = bbpoVisitnum;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column BbsPost.bbpo_replynum
     * @return  the value of BbsPost.bbpo_replynum
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public Integer getBbpoReplynum() {
        return bbpoReplynum;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column BbsPost.bbpo_replynum
     * @param bbpoReplynum  the value for BbsPost.bbpo_replynum
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public void setBbpoReplynum(Integer bbpoReplynum) {
        this.bbpoReplynum = bbpoReplynum;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column BbsPost.bbpo_isbest
     * @return  the value of BbsPost.bbpo_isbest
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public Boolean getBbpoIsbest() {
        return bbpoIsbest;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column BbsPost.bbpo_isbest
     * @param bbpoIsbest  the value for BbsPost.bbpo_isbest
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public void setBbpoIsbest(Boolean bbpoIsbest) {
        this.bbpoIsbest = bbpoIsbest;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column BbsPost.bbpo_istop
     * @return  the value of BbsPost.bbpo_istop
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public Boolean getBbpoIstop() {
        return bbpoIstop;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column BbsPost.bbpo_istop
     * @param bbpoIstop  the value for BbsPost.bbpo_istop
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public void setBbpoIstop(Boolean bbpoIstop) {
        this.bbpoIstop = bbpoIstop;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column BbsPost.bbpo_hasattach
     * @return  the value of BbsPost.bbpo_hasattach
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public Boolean getBbpoHasattach() {
        return bbpoHasattach;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column BbsPost.bbpo_hasattach
     * @param bbpoHasattach  the value for BbsPost.bbpo_hasattach
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public void setBbpoHasattach(Boolean bbpoHasattach) {
        this.bbpoHasattach = bbpoHasattach;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column BbsPost.bbpo_content
     * @return  the value of BbsPost.bbpo_content
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public String getBbpoContent() {
        return bbpoContent;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column BbsPost.bbpo_content
     * @param bbpoContent  the value for BbsPost.bbpo_content
     * @mbggenerated  Fri Jul 05 13:54:19 GMT+08:00 2013
     */
    public void setBbpoContent(String bbpoContent) {
        this.bbpoContent = bbpoContent;
    }
}