package com.recom.domain;

import java.util.Date;

public class Chapter {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Chapter.chap_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer chapId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Chapter.chap_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer chapCourId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Chapter.chap_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String chapName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Chapter.chap_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String chapOrdinal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Chapter.chap_state
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer chapState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Chapter.chap_createtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date chapCreatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Chapter.chap_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String chapDescribe;
	/**
	 * 章节综合评分
	 */
	private Double chapAssessScore;
	/**
	 * 章节评价次数
	 */
	private int chapAssessNum;
	
	
	public Double getChapAssessScore() {
        return chapAssessScore;
    }

    public void setChapAssessScore(Double chapAssessScore) {
        this.chapAssessScore = chapAssessScore;
    }

    public int getChapAssessNum() {
        return chapAssessNum;
    }

    public void setChapAssessNum(int chapAssessNum) {
        this.chapAssessNum = chapAssessNum;
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Chapter.chap_id
	 * @return  the value of Chapter.chap_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getChapId() {
		return chapId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Chapter.chap_id
	 * @param chapId  the value for Chapter.chap_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setChapId(Integer chapId) {
		this.chapId = chapId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Chapter.chap_cour_id
	 * @return  the value of Chapter.chap_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getChapCourId() {
		return chapCourId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Chapter.chap_cour_id
	 * @param chapCourId  the value for Chapter.chap_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setChapCourId(Integer chapCourId) {
		this.chapCourId = chapCourId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Chapter.chap_name
	 * @return  the value of Chapter.chap_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getChapName() {
		return chapName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Chapter.chap_name
	 * @param chapName  the value for Chapter.chap_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setChapName(String chapName) {
		this.chapName = chapName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Chapter.chap_ordinal
	 * @return  the value of Chapter.chap_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getChapOrdinal() {
		return chapOrdinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Chapter.chap_ordinal
	 * @param chapOrdinal  the value for Chapter.chap_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setChapOrdinal(String chapOrdinal) {
		this.chapOrdinal = chapOrdinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Chapter.chap_state
	 * @return  the value of Chapter.chap_state
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getChapState() {
		return chapState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Chapter.chap_state
	 * @param chapState  the value for Chapter.chap_state
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setChapState(Integer chapState) {
		this.chapState = chapState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Chapter.chap_createtime
	 * @return  the value of Chapter.chap_createtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getChapCreatetime() {
		return chapCreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Chapter.chap_createtime
	 * @param chapCreatetime  the value for Chapter.chap_createtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setChapCreatetime(Date chapCreatetime) {
		this.chapCreatetime = chapCreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Chapter.chap_describe
	 * @return  the value of Chapter.chap_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getChapDescribe() {
		return chapDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Chapter.chap_describe
	 * @param chapDescribe  the value for Chapter.chap_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setChapDescribe(String chapDescribe) {
		this.chapDescribe = chapDescribe;
	}
}