package com.recom.domain;

import java.util.Date;

public class Course {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Course.cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer courId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Course.cour_cateIds
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String courCateids;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Course.cour_tepa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer courTepaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Course.cour_code
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String courCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Course.cour_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String courName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Course.cour_credit
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Float courCredit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Course.cour_teacher_ids
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String courTeacherIds;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Course.cour_mentro_teaids
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String courMentroTeaids;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Course.cour_time_schedule
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String courTimeSchedule;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Course.cour_state
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer courState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Course.cour_create_userid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer courCreateUserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Course.cour_create_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date courCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Course.cour_poston
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Boolean courPoston;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Course.cour_forumName
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String courForumname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Course.cour_verify
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer courVerify;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Course.cour_coverPictureId
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer courCoverpictureid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Course.cour_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String courDescribe;

	/**
	 * 课程是否对外开放
	 * 0表示仅对创建者的机构（及其下属机构）开放，1表示对全市开放
	 */
	private Boolean courOpenToAll;
	
	/**
	 * 课程的选课人数
	 */
	private Integer courChooseNum;
	
	/**
	 * 参加该课程考试的分数限制
	 */
	private Float courTestLimitScore;
	/**
	 * 课程评价分数
	 */
	private Double courAssessScore;
	/**
	 * 课程类别描述，比如XIA,表示选修IA
	 */
	private String courType;
	/**
     * 课程的学年
     */
	private int courYear;
	/**
     * 课程的学期
     */
	private int courTerm;
	/**
     * 课程的学段
     */
	private int courStudyPhase;
	/**
     * 课程的文理方向
     */
	private int courArtScience;
	
	public int getCourYear() {
        return courYear;
    }

    public void setCourYear(int courYear) {
        this.courYear = courYear;
    }

    public int getCourTerm() {
        return courTerm;
    }

    public void setCourTerm(int courTerm) {
        this.courTerm = courTerm;
    }

    public int getCourStudyPhase() {
        return courStudyPhase;
    }

    public void setCourStudyPhase(int courStudyPhase) {
        this.courStudyPhase = courStudyPhase;
    }

    public int getCourArtScience() {
        return courArtScience;
    }

    public void setCourArtScience(int courArtScience) {
        this.courArtScience = courArtScience;
    }

    public String getCourType() {
        return courType;
    }

    public void setCourType(String courType) {
        this.courType = courType;
    }

    public Double getCourAssessScore() {
        return courAssessScore;
    }

    public void setCourAssessScore(Double courAssessScore) {
        this.courAssessScore = courAssessScore;
    }

    public Float getCourTestLimitScore() {
        return courTestLimitScore;
    }

    public void setCourTestLimitScore(Float courTestLimitScore) {
        this.courTestLimitScore = courTestLimitScore;
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Course.cour_id
	 * @return  the value of Course.cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getCourId() {
		return courId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Course.cour_id
	 * @param courId  the value for Course.cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCourId(Integer courId) {
		this.courId = courId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Course.cour_cateIds
	 * @return  the value of Course.cour_cateIds
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getCourCateids() {
		return courCateids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Course.cour_cateIds
	 * @param courCateids  the value for Course.cour_cateIds
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCourCateids(String courCateids) {
		this.courCateids = courCateids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Course.cour_tepa_id
	 * @return  the value of Course.cour_tepa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getCourTepaId() {
		return courTepaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Course.cour_tepa_id
	 * @param courTepaId  the value for Course.cour_tepa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCourTepaId(Integer courTepaId) {
		this.courTepaId = courTepaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Course.cour_code
	 * @return  the value of Course.cour_code
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getCourCode() {
		return courCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Course.cour_code
	 * @param courCode  the value for Course.cour_code
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCourCode(String courCode) {
		this.courCode = courCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Course.cour_name
	 * @return  the value of Course.cour_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getCourName() {
		return courName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Course.cour_name
	 * @param courName  the value for Course.cour_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCourName(String courName) {
		this.courName = courName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Course.cour_credit
	 * @return  the value of Course.cour_credit
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Float getCourCredit() {
		return courCredit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Course.cour_credit
	 * @param courCredit  the value for Course.cour_credit
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCourCredit(Float courCredit) {
		this.courCredit = courCredit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Course.cour_teacher_ids
	 * @return  the value of Course.cour_teacher_ids
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getCourTeacherIds() {
		return courTeacherIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Course.cour_teacher_ids
	 * @param courTeacherIds  the value for Course.cour_teacher_ids
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCourTeacherIds(String courTeacherIds) {
		this.courTeacherIds = courTeacherIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Course.cour_mentro_teaids
	 * @return  the value of Course.cour_mentro_teaids
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getCourMentroTeaids() {
		return courMentroTeaids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Course.cour_mentro_teaids
	 * @param courMentroTeaids  the value for Course.cour_mentro_teaids
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCourMentroTeaids(String courMentroTeaids) {
		this.courMentroTeaids = courMentroTeaids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Course.cour_time_schedule
	 * @return  the value of Course.cour_time_schedule
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getCourTimeSchedule() {
		return courTimeSchedule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Course.cour_time_schedule
	 * @param courTimeSchedule  the value for Course.cour_time_schedule
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCourTimeSchedule(String courTimeSchedule) {
		this.courTimeSchedule = courTimeSchedule;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Course.cour_state
	 * @return  the value of Course.cour_state
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getCourState() {
		return courState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Course.cour_state
	 * @param courState  the value for Course.cour_state
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCourState(Integer courState) {
		this.courState = courState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Course.cour_create_userid
	 * @return  the value of Course.cour_create_userid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getCourCreateUserid() {
		return courCreateUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Course.cour_create_userid
	 * @param courCreateUserid  the value for Course.cour_create_userid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCourCreateUserid(Integer courCreateUserid) {
		this.courCreateUserid = courCreateUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Course.cour_create_time
	 * @return  the value of Course.cour_create_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getCourCreateTime() {
		return courCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Course.cour_create_time
	 * @param courCreateTime  the value for Course.cour_create_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCourCreateTime(Date courCreateTime) {
		this.courCreateTime = courCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Course.cour_poston
	 * @return  the value of Course.cour_poston
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Boolean getCourPoston() {
		return courPoston;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Course.cour_poston
	 * @param courPoston  the value for Course.cour_poston
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCourPoston(Boolean courPoston) {
		this.courPoston = courPoston;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Course.cour_forumName
	 * @return  the value of Course.cour_forumName
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getCourForumname() {
		return courForumname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Course.cour_forumName
	 * @param courForumname  the value for Course.cour_forumName
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCourForumname(String courForumname) {
		this.courForumname = courForumname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Course.cour_verify
	 * @return  the value of Course.cour_verify
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getCourVerify() {
		return courVerify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Course.cour_verify
	 * @param courVerify  the value for Course.cour_verify
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCourVerify(Integer courVerify) {
		this.courVerify = courVerify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Course.cour_coverPictureId
	 * @return  the value of Course.cour_coverPictureId
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getCourCoverpictureid() {
		return courCoverpictureid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Course.cour_coverPictureId
	 * @param courCoverpictureid  the value for Course.cour_coverPictureId
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCourCoverpictureid(Integer courCoverpictureid) {
		this.courCoverpictureid = courCoverpictureid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Course.cour_describe
	 * @return  the value of Course.cour_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getCourDescribe() {
		return courDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Course.cour_describe
	 * @param courDescribe  the value for Course.cour_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCourDescribe(String courDescribe) {
		this.courDescribe = courDescribe;
	}

    public Boolean getCourOpenToAll() {
        return courOpenToAll;
    }

    public void setCourOpenToAll(Boolean courOpenToAll) {
        this.courOpenToAll = courOpenToAll;
    }

    public Integer getCourChooseNum() {
        return courChooseNum;
    }

    public void setCourChooseNum(Integer courChooseNum) {
        this.courChooseNum = courChooseNum;
    }
	
}