package com.recom.domain;

import java.util.Date;

public class CourseSelectInformation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CourseSelectInformation.csin_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer csinId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CourseSelectInformation.csin_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer csinCourId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CourseSelectInformation.csin_depa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer csinDepaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CourseSelectInformation.csin_year
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer csinYear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CourseSelectInformation.csin_pubtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date csinPubtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CourseSelectInformation.csin_opentime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date csinOpentime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CourseSelectInformation.csin_closetime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date csinClosetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CourseSelectInformation.csin_on
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Boolean csinOn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CourseSelectInformation.csin_remark
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String csinRemark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CourseSelectInformation.csin_id
	 * @return  the value of CourseSelectInformation.csin_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getCsinId() {
		return csinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CourseSelectInformation.csin_id
	 * @param csinId  the value for CourseSelectInformation.csin_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCsinId(Integer csinId) {
		this.csinId = csinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CourseSelectInformation.csin_cour_id
	 * @return  the value of CourseSelectInformation.csin_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getCsinCourId() {
		return csinCourId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CourseSelectInformation.csin_cour_id
	 * @param csinCourId  the value for CourseSelectInformation.csin_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCsinCourId(Integer csinCourId) {
		this.csinCourId = csinCourId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CourseSelectInformation.csin_depa_id
	 * @return  the value of CourseSelectInformation.csin_depa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getCsinDepaId() {
		return csinDepaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CourseSelectInformation.csin_depa_id
	 * @param csinDepaId  the value for CourseSelectInformation.csin_depa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCsinDepaId(Integer csinDepaId) {
		this.csinDepaId = csinDepaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CourseSelectInformation.csin_year
	 * @return  the value of CourseSelectInformation.csin_year
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getCsinYear() {
		return csinYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CourseSelectInformation.csin_year
	 * @param csinYear  the value for CourseSelectInformation.csin_year
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCsinYear(Integer csinYear) {
		this.csinYear = csinYear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CourseSelectInformation.csin_pubtime
	 * @return  the value of CourseSelectInformation.csin_pubtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getCsinPubtime() {
		return csinPubtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CourseSelectInformation.csin_pubtime
	 * @param csinPubtime  the value for CourseSelectInformation.csin_pubtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCsinPubtime(Date csinPubtime) {
		this.csinPubtime = csinPubtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CourseSelectInformation.csin_opentime
	 * @return  the value of CourseSelectInformation.csin_opentime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getCsinOpentime() {
		return csinOpentime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CourseSelectInformation.csin_opentime
	 * @param csinOpentime  the value for CourseSelectInformation.csin_opentime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCsinOpentime(Date csinOpentime) {
		this.csinOpentime = csinOpentime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CourseSelectInformation.csin_closetime
	 * @return  the value of CourseSelectInformation.csin_closetime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getCsinClosetime() {
		return csinClosetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CourseSelectInformation.csin_closetime
	 * @param csinClosetime  the value for CourseSelectInformation.csin_closetime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCsinClosetime(Date csinClosetime) {
		this.csinClosetime = csinClosetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CourseSelectInformation.csin_on
	 * @return  the value of CourseSelectInformation.csin_on
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Boolean getCsinOn() {
		return csinOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CourseSelectInformation.csin_on
	 * @param csinOn  the value for CourseSelectInformation.csin_on
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCsinOn(Boolean csinOn) {
		this.csinOn = csinOn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CourseSelectInformation.csin_remark
	 * @return  the value of CourseSelectInformation.csin_remark
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getCsinRemark() {
		return csinRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CourseSelectInformation.csin_remark
	 * @param csinRemark  the value for CourseSelectInformation.csin_remark
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCsinRemark(String csinRemark) {
		this.csinRemark = csinRemark;
	}
}