package com.recom.domain;

import java.util.Date;

public class CourseCategory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CourseCategory.coca_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer cocaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CourseCategory.coca_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String cocaName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CourseCategory.coca_code
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String cocaCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CourseCategory.coca_create_userid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer cocaCreateUserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CourseCategory.coca_create_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date cocaCreateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CourseCategory.coca_state
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer cocaState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column CourseCategory.coca_descirbe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String cocaDescirbe;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CourseCategory.coca_id
	 * @return  the value of CourseCategory.coca_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getCocaId() {
		return cocaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CourseCategory.coca_id
	 * @param cocaId  the value for CourseCategory.coca_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCocaId(Integer cocaId) {
		this.cocaId = cocaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CourseCategory.coca_name
	 * @return  the value of CourseCategory.coca_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getCocaName() {
		return cocaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CourseCategory.coca_name
	 * @param cocaName  the value for CourseCategory.coca_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCocaName(String cocaName) {
		this.cocaName = cocaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CourseCategory.coca_code
	 * @return  the value of CourseCategory.coca_code
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getCocaCode() {
		return cocaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CourseCategory.coca_code
	 * @param cocaCode  the value for CourseCategory.coca_code
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCocaCode(String cocaCode) {
		this.cocaCode = cocaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CourseCategory.coca_create_userid
	 * @return  the value of CourseCategory.coca_create_userid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getCocaCreateUserid() {
		return cocaCreateUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CourseCategory.coca_create_userid
	 * @param cocaCreateUserid  the value for CourseCategory.coca_create_userid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCocaCreateUserid(Integer cocaCreateUserid) {
		this.cocaCreateUserid = cocaCreateUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CourseCategory.coca_create_time
	 * @return  the value of CourseCategory.coca_create_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getCocaCreateTime() {
		return cocaCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CourseCategory.coca_create_time
	 * @param cocaCreateTime  the value for CourseCategory.coca_create_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCocaCreateTime(Date cocaCreateTime) {
		this.cocaCreateTime = cocaCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CourseCategory.coca_state
	 * @return  the value of CourseCategory.coca_state
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getCocaState() {
		return cocaState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CourseCategory.coca_state
	 * @param cocaState  the value for CourseCategory.coca_state
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCocaState(Integer cocaState) {
		this.cocaState = cocaState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column CourseCategory.coca_descirbe
	 * @return  the value of CourseCategory.coca_descirbe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getCocaDescirbe() {
		return cocaDescirbe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column CourseCategory.coca_descirbe
	 * @param cocaDescirbe  the value for CourseCategory.coca_descirbe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setCocaDescirbe(String cocaDescirbe) {
		this.cocaDescirbe = cocaDescirbe;
	}
}