package com.recom.domain;

public class Department {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Department.depa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer depaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Department.depa_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String depaName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Department.depa_abbreviation
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String depaAbbreviation;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Department.depa_code
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String depaCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Department.depa_parent_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer depaParentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Department.depa_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer depaType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Department.depa_id
	 * @return  the value of Department.depa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getDepaId() {
		return depaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Department.depa_id
	 * @param depaId  the value for Department.depa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setDepaId(Integer depaId) {
		this.depaId = depaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Department.depa_name
	 * @return  the value of Department.depa_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getDepaName() {
		return depaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Department.depa_name
	 * @param depaName  the value for Department.depa_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setDepaName(String depaName) {
		this.depaName = depaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Department.depa_abbreviation
	 * @return  the value of Department.depa_abbreviation
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getDepaAbbreviation() {
		return depaAbbreviation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Department.depa_abbreviation
	 * @param depaAbbreviation  the value for Department.depa_abbreviation
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setDepaAbbreviation(String depaAbbreviation) {
		this.depaAbbreviation = depaAbbreviation;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Department.depa_code
	 * @return  the value of Department.depa_code
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getDepaCode() {
		return depaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Department.depa_code
	 * @param depaCode  the value for Department.depa_code
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setDepaCode(String depaCode) {
		this.depaCode = depaCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Department.depa_parent_id
	 * @return  the value of Department.depa_parent_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getDepaParentId() {
		return depaParentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Department.depa_parent_id
	 * @param depaParentId  the value for Department.depa_parent_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setDepaParentId(Integer depaParentId) {
		this.depaParentId = depaParentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Department.depa_type
	 * @return  the value of Department.depa_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getDepaType() {
		return depaType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Department.depa_type
	 * @param depaType  the value for Department.depa_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setDepaType(Integer depaType) {
		this.depaType = depaType;
	}
}