package com.recom.domain;

public class EvaluateMethod {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EvaluateMethod.evme_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer evmeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EvaluateMethod.evme_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String evmeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EvaluateMethod.evme_pattern
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String evmePattern;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EvaluateMethod.evme_threhold
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String evmeThrehold;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column EvaluateMethod.evme_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String evmeDescribe;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EvaluateMethod.evme_id
	 * @return  the value of EvaluateMethod.evme_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getEvmeId() {
		return evmeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EvaluateMethod.evme_id
	 * @param evmeId  the value for EvaluateMethod.evme_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setEvmeId(Integer evmeId) {
		this.evmeId = evmeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EvaluateMethod.evme_name
	 * @return  the value of EvaluateMethod.evme_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getEvmeName() {
		return evmeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EvaluateMethod.evme_name
	 * @param evmeName  the value for EvaluateMethod.evme_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setEvmeName(String evmeName) {
		this.evmeName = evmeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EvaluateMethod.evme_pattern
	 * @return  the value of EvaluateMethod.evme_pattern
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getEvmePattern() {
		return evmePattern;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EvaluateMethod.evme_pattern
	 * @param evmePattern  the value for EvaluateMethod.evme_pattern
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setEvmePattern(String evmePattern) {
		this.evmePattern = evmePattern;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EvaluateMethod.evme_threhold
	 * @return  the value of EvaluateMethod.evme_threhold
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getEvmeThrehold() {
		return evmeThrehold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EvaluateMethod.evme_threhold
	 * @param evmeThrehold  the value for EvaluateMethod.evme_threhold
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setEvmeThrehold(String evmeThrehold) {
		this.evmeThrehold = evmeThrehold;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column EvaluateMethod.evme_describe
	 * @return  the value of EvaluateMethod.evme_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getEvmeDescribe() {
		return evmeDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column EvaluateMethod.evme_describe
	 * @param evmeDescribe  the value for EvaluateMethod.evme_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setEvmeDescribe(String evmeDescribe) {
		this.evmeDescribe = evmeDescribe;
	}
}