package com.recom.domain;

import java.util.Date;

public class ExamPaper {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamPaper.expa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer expaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamPaper.expa_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer expaCourId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamPaper.expa_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer expaOrdinal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamPaper.expa_difficulty
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer expaDifficulty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamPaper.expa_totalscore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer expaTotalscore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamPaper.expa_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String expaName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamPaper.expa_createtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date expaCreatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamPaper.expa_create_userid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer expaCreateUserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamPaper.expa_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer expaType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamPaper.expa_gppa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer expaGppaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ExamPaper.expa_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String expaDescribe;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamPaper.expa_id
	 * @return  the value of ExamPaper.expa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getExpaId() {
		return expaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamPaper.expa_id
	 * @param expaId  the value for ExamPaper.expa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExpaId(Integer expaId) {
		this.expaId = expaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamPaper.expa_cour_id
	 * @return  the value of ExamPaper.expa_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getExpaCourId() {
		return expaCourId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamPaper.expa_cour_id
	 * @param expaCourId  the value for ExamPaper.expa_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExpaCourId(Integer expaCourId) {
		this.expaCourId = expaCourId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamPaper.expa_ordinal
	 * @return  the value of ExamPaper.expa_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getExpaOrdinal() {
		return expaOrdinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamPaper.expa_ordinal
	 * @param expaOrdinal  the value for ExamPaper.expa_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExpaOrdinal(Integer expaOrdinal) {
		this.expaOrdinal = expaOrdinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamPaper.expa_difficulty
	 * @return  the value of ExamPaper.expa_difficulty
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getExpaDifficulty() {
		return expaDifficulty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamPaper.expa_difficulty
	 * @param expaDifficulty  the value for ExamPaper.expa_difficulty
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExpaDifficulty(Integer expaDifficulty) {
		this.expaDifficulty = expaDifficulty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamPaper.expa_totalscore
	 * @return  the value of ExamPaper.expa_totalscore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getExpaTotalscore() {
		return expaTotalscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamPaper.expa_totalscore
	 * @param expaTotalscore  the value for ExamPaper.expa_totalscore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExpaTotalscore(Integer expaTotalscore) {
		this.expaTotalscore = expaTotalscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamPaper.expa_name
	 * @return  the value of ExamPaper.expa_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getExpaName() {
		return expaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamPaper.expa_name
	 * @param expaName  the value for ExamPaper.expa_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExpaName(String expaName) {
		this.expaName = expaName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamPaper.expa_createtime
	 * @return  the value of ExamPaper.expa_createtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getExpaCreatetime() {
		return expaCreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamPaper.expa_createtime
	 * @param expaCreatetime  the value for ExamPaper.expa_createtime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExpaCreatetime(Date expaCreatetime) {
		this.expaCreatetime = expaCreatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamPaper.expa_create_userid
	 * @return  the value of ExamPaper.expa_create_userid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getExpaCreateUserid() {
		return expaCreateUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamPaper.expa_create_userid
	 * @param expaCreateUserid  the value for ExamPaper.expa_create_userid
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExpaCreateUserid(Integer expaCreateUserid) {
		this.expaCreateUserid = expaCreateUserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamPaper.expa_type
	 * @return  the value of ExamPaper.expa_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getExpaType() {
		return expaType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamPaper.expa_type
	 * @param expaType  the value for ExamPaper.expa_type
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExpaType(Integer expaType) {
		this.expaType = expaType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamPaper.expa_gppa_id
	 * @return  the value of ExamPaper.expa_gppa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getExpaGppaId() {
		return expaGppaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamPaper.expa_gppa_id
	 * @param expaGppaId  the value for ExamPaper.expa_gppa_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExpaGppaId(Integer expaGppaId) {
		this.expaGppaId = expaGppaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ExamPaper.expa_describe
	 * @return  the value of ExamPaper.expa_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getExpaDescribe() {
		return expaDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ExamPaper.expa_describe
	 * @param expaDescribe  the value for ExamPaper.expa_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setExpaDescribe(String expaDescribe) {
		this.expaDescribe = expaDescribe;
	}
}