package com.recom.domain;

public class Option {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Option.opti_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer optiId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Option.opti_ques_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer optiQuesId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Option.opti_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String optiDescribe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Option.opti_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer optiOrdinal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Option.opti_attachment
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Boolean optiAttachment;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Option.opti_id
	 * @return  the value of Option.opti_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getOptiId() {
		return optiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Option.opti_id
	 * @param optiId  the value for Option.opti_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setOptiId(Integer optiId) {
		this.optiId = optiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Option.opti_ques_id
	 * @return  the value of Option.opti_ques_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getOptiQuesId() {
		return optiQuesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Option.opti_ques_id
	 * @param optiQuesId  the value for Option.opti_ques_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setOptiQuesId(Integer optiQuesId) {
		this.optiQuesId = optiQuesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Option.opti_describe
	 * @return  the value of Option.opti_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getOptiDescribe() {
		return optiDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Option.opti_describe
	 * @param optiDescribe  the value for Option.opti_describe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setOptiDescribe(String optiDescribe) {
		this.optiDescribe = optiDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Option.opti_ordinal
	 * @return  the value of Option.opti_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getOptiOrdinal() {
		return optiOrdinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Option.opti_ordinal
	 * @param optiOrdinal  the value for Option.opti_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setOptiOrdinal(Integer optiOrdinal) {
		this.optiOrdinal = optiOrdinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Option.opti_attachment
	 * @return  the value of Option.opti_attachment
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Boolean getOptiAttachment() {
		return optiAttachment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Option.opti_attachment
	 * @param optiAttachment  the value for Option.opti_attachment
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setOptiAttachment(Boolean optiAttachment) {
		this.optiAttachment = optiAttachment;
	}
}