package com.recom.domain;

import java.util.Date;

public class ReAutoTest {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_AutoTest.rate_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer rateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_AutoTest.rate_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer rateUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_AutoTest.rate_exin_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer rateExinId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_AutoTest.rate_score
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Float rateScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_AutoTest.rate_starttime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date rateStarttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_AutoTest.rate_submittime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date rateSubmittime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_AutoTest.rate_isfinished
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Boolean rateIsfinished;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_AutoTest.rate_id
	 * @return  the value of Re_AutoTest.rate_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getRateId() {
		return rateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_AutoTest.rate_id
	 * @param rateId  the value for Re_AutoTest.rate_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRateId(Integer rateId) {
		this.rateId = rateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_AutoTest.rate_user_id
	 * @return  the value of Re_AutoTest.rate_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getRateUserId() {
		return rateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_AutoTest.rate_user_id
	 * @param rateUserId  the value for Re_AutoTest.rate_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRateUserId(Integer rateUserId) {
		this.rateUserId = rateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_AutoTest.rate_exin_id
	 * @return  the value of Re_AutoTest.rate_exin_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getRateExinId() {
		return rateExinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_AutoTest.rate_exin_id
	 * @param rateExinId  the value for Re_AutoTest.rate_exin_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRateExinId(Integer rateExinId) {
		this.rateExinId = rateExinId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_AutoTest.rate_score
	 * @return  the value of Re_AutoTest.rate_score
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Float getRateScore() {
		return rateScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_AutoTest.rate_score
	 * @param rateScore  the value for Re_AutoTest.rate_score
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRateScore(Float rateScore) {
		this.rateScore = rateScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_AutoTest.rate_starttime
	 * @return  the value of Re_AutoTest.rate_starttime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getRateStarttime() {
		return rateStarttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_AutoTest.rate_starttime
	 * @param rateStarttime  the value for Re_AutoTest.rate_starttime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRateStarttime(Date rateStarttime) {
		this.rateStarttime = rateStarttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_AutoTest.rate_submittime
	 * @return  the value of Re_AutoTest.rate_submittime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getRateSubmittime() {
		return rateSubmittime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_AutoTest.rate_submittime
	 * @param rateSubmittime  the value for Re_AutoTest.rate_submittime
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRateSubmittime(Date rateSubmittime) {
		this.rateSubmittime = rateSubmittime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_AutoTest.rate_isfinished
	 * @return  the value of Re_AutoTest.rate_isfinished
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Boolean getRateIsfinished() {
		return rateIsfinished;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_AutoTest.rate_isfinished
	 * @param rateIsfinished  the value for Re_AutoTest.rate_isfinished
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRateIsfinished(Boolean rateIsfinished) {
		this.rateIsfinished = rateIsfinished;
	}
}