package com.recom.domain;

import java.util.Date;

public class ReSelectCourse {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_SelectCource.rsco_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer rscoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_SelectCource.rsco_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer rscoUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_SelectCource.rsco_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer rscoCourId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_SelectCource.rsco_verify
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer rscoVerify;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_SelectCource.rsco_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date rscoTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_SelectCource.rsco_massedLearnScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Float rscoMassedlearnscore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_SelectCource.rsco_loginScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Float rscoLoginscore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_SelectCource.rsco_learnTimeScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Float rscoLearntimescore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_SelectCource.rsco_bbsDiscussScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Float rscoBbsdiscussscore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_SelectCource.rsco_subAssessScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Float rscoSubassessscore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_SelectCource.rsco_testScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Float rscoTestscore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_SelectCource.rsco_totalScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Float rscoTotalscore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_SelectCource.rsco_state
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer rscoState;
	/**
	 * 标识成绩是否改变，用户批量更新成绩
	 */
	private boolean scoreChanged=false;
	/**
	 * 标识选课是否有效，1表示有效，2表示无效（退课的情况）
	 */
	private int rscoValid;
	/**
     * 选课人的机构（学校）名称
     */
	private String rscoDepartName;
	/**
     * 选课人的班级名称
     */
	private String rscoClassName;
	/**
     * 选课人的年级名称
     */
	private String rscoGradeName;
	/**
     * 选课人的年级id
     */
	private int rscoGradeId;
	
    public String getRscoDepartName() {
        return rscoDepartName;
    }

    public void setRscoDepartName(String rscoDepartName) {
        this.rscoDepartName = rscoDepartName;
    }

    public String getRscoClassName() {
        return rscoClassName;
    }

    public void setRscoClassName(String rscoClassName) {
        this.rscoClassName = rscoClassName;
    }

    public String getRscoGradeName() {
        return rscoGradeName;
    }

    public void setRscoGradeName(String rscoGradeName) {
        this.rscoGradeName = rscoGradeName;
    }

    public int getRscoGradeId() {
        return rscoGradeId;
    }

    public void setRscoGradeId(int rscoGradeId) {
        this.rscoGradeId = rscoGradeId;
    }

    public boolean isScoreChanged() {
        return scoreChanged;
    }

    public void setScoreChanged(boolean scoreChanged) {
        this.scoreChanged = scoreChanged;
    }

    public int getRscoValid() {
        return rscoValid;
    }

    public void setRscoValid(int rscoValid) {
        this.rscoValid = rscoValid;
    }

    /**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_SelectCource.rsco_id
	 * @return  the value of Re_SelectCource.rsco_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getRscoId() {
		return rscoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_SelectCource.rsco_id
	 * @param rscoId  the value for Re_SelectCource.rsco_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRscoId(Integer rscoId) {
		this.rscoId = rscoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_SelectCource.rsco_user_id
	 * @return  the value of Re_SelectCource.rsco_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getRscoUserId() {
		return rscoUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_SelectCource.rsco_user_id
	 * @param rscoUserId  the value for Re_SelectCource.rsco_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRscoUserId(Integer rscoUserId) {
		this.rscoUserId = rscoUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_SelectCource.rsco_cour_id
	 * @return  the value of Re_SelectCource.rsco_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getRscoCourId() {
		return rscoCourId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_SelectCource.rsco_cour_id
	 * @param rscoCourId  the value for Re_SelectCource.rsco_cour_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRscoCourId(Integer rscoCourId) {
		this.rscoCourId = rscoCourId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_SelectCource.rsco_verify
	 * @return  the value of Re_SelectCource.rsco_verify
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getRscoVerify() {
		return rscoVerify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_SelectCource.rsco_verify
	 * @param rscoVerify  the value for Re_SelectCource.rsco_verify
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRscoVerify(Integer rscoVerify) {
		this.rscoVerify = rscoVerify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_SelectCource.rsco_time
	 * @return  the value of Re_SelectCource.rsco_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getRscoTime() {
		return rscoTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_SelectCource.rsco_time
	 * @param rscoTime  the value for Re_SelectCource.rsco_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRscoTime(Date rscoTime) {
		this.rscoTime = rscoTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_SelectCource.rsco_massedLearnScore
	 * @return  the value of Re_SelectCource.rsco_massedLearnScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Float getRscoMassedlearnscore() {
		return rscoMassedlearnscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_SelectCource.rsco_massedLearnScore
	 * @param rscoMassedlearnscore  the value for Re_SelectCource.rsco_massedLearnScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRscoMassedlearnscore(Float rscoMassedlearnscore) {
		this.rscoMassedlearnscore = rscoMassedlearnscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_SelectCource.rsco_loginScore
	 * @return  the value of Re_SelectCource.rsco_loginScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Float getRscoLoginscore() {
		return rscoLoginscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_SelectCource.rsco_loginScore
	 * @param rscoLoginscore  the value for Re_SelectCource.rsco_loginScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRscoLoginscore(Float rscoLoginscore) {
		this.rscoLoginscore = rscoLoginscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_SelectCource.rsco_learnTimeScore
	 * @return  the value of Re_SelectCource.rsco_learnTimeScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Float getRscoLearntimescore() {
		return rscoLearntimescore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_SelectCource.rsco_learnTimeScore
	 * @param rscoLearntimescore  the value for Re_SelectCource.rsco_learnTimeScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRscoLearntimescore(Float rscoLearntimescore) {
		this.rscoLearntimescore = rscoLearntimescore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_SelectCource.rsco_bbsDiscussScore
	 * @return  the value of Re_SelectCource.rsco_bbsDiscussScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Float getRscoBbsdiscussscore() {
		return rscoBbsdiscussscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_SelectCource.rsco_bbsDiscussScore
	 * @param rscoBbsdiscussscore  the value for Re_SelectCource.rsco_bbsDiscussScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRscoBbsdiscussscore(Float rscoBbsdiscussscore) {
		this.rscoBbsdiscussscore = rscoBbsdiscussscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_SelectCource.rsco_subAssessScore
	 * @return  the value of Re_SelectCource.rsco_subAssessScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Float getRscoSubassessscore() {
		return rscoSubassessscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_SelectCource.rsco_subAssessScore
	 * @param rscoSubassessscore  the value for Re_SelectCource.rsco_subAssessScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRscoSubassessscore(Float rscoSubassessscore) {
		this.rscoSubassessscore = rscoSubassessscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_SelectCource.rsco_testScore
	 * @return  the value of Re_SelectCource.rsco_testScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Float getRscoTestscore() {
		return rscoTestscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_SelectCource.rsco_testScore
	 * @param rscoTestscore  the value for Re_SelectCource.rsco_testScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRscoTestscore(Float rscoTestscore) {
		this.rscoTestscore = rscoTestscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_SelectCource.rsco_totalScore
	 * @return  the value of Re_SelectCource.rsco_totalScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Float getRscoTotalscore() {
		return rscoTotalscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_SelectCource.rsco_totalScore
	 * @param rscoTotalscore  the value for Re_SelectCource.rsco_totalScore
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRscoTotalscore(Float rscoTotalscore) {
		this.rscoTotalscore = rscoTotalscore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_SelectCource.rsco_state
	 * @return  the value of Re_SelectCource.rsco_state
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getRscoState() {
		return rscoState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_SelectCource.rsco_state
	 * @param rscoState  the value for Re_SelectCource.rsco_state
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRscoState(Integer rscoState) {
		this.rscoState = rscoState;
	}
}