package com.recom.domain;

import java.util.Date;

public class ReUserRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_UserRole.rero_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer reroId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_UserRole.rero_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer reroUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_UserRole.rero_role_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer reroRoleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Re_UserRole.rero_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Date reroTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_UserRole.rero_id
	 * @return  the value of Re_UserRole.rero_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getReroId() {
		return reroId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_UserRole.rero_id
	 * @param reroId  the value for Re_UserRole.rero_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setReroId(Integer reroId) {
		this.reroId = reroId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_UserRole.rero_user_id
	 * @return  the value of Re_UserRole.rero_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getReroUserId() {
		return reroUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_UserRole.rero_user_id
	 * @param reroUserId  the value for Re_UserRole.rero_user_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setReroUserId(Integer reroUserId) {
		this.reroUserId = reroUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_UserRole.rero_role_id
	 * @return  the value of Re_UserRole.rero_role_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getReroRoleId() {
		return reroRoleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_UserRole.rero_role_id
	 * @param reroRoleId  the value for Re_UserRole.rero_role_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setReroRoleId(Integer reroRoleId) {
		this.reroRoleId = reroRoleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Re_UserRole.rero_time
	 * @return  the value of Re_UserRole.rero_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Date getReroTime() {
		return reroTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Re_UserRole.rero_time
	 * @param reroTime  the value for Re_UserRole.rero_time
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setReroTime(Date reroTime) {
		this.reroTime = reroTime;
	}
}