package com.recom.domain;

public class Role {

	/**	数据库内置的角色 **/
	public static final int ROLE_STUDENT = 1;
	public static final int ROLE_TEACHER = 2;
	public static final int ROLE_TEACHING_MANAGER = 3;//教务管理员
	public static final int ROLE_SYSTEM_MANAGER = 4;//系统管理员
	public static final int ROLE_ADMINISTRATOR = 5;//超级用户
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Role.role_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Role.role_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String roleName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Role.role_descirbe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String roleDescirbe;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Role.role_id
	 * @return  the value of Role.role_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Role.role_id
	 * @param roleId  the value for Role.role_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Role.role_name
	 * @return  the value of Role.role_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Role.role_name
	 * @param roleName  the value for Role.role_name
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Role.role_descirbe
	 * @return  the value of Role.role_descirbe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getRoleDescirbe() {
		return roleDescirbe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Role.role_descirbe
	 * @param roleDescirbe  the value for Role.role_descirbe
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setRoleDescirbe(String roleDescirbe) {
		this.roleDescirbe = roleDescirbe;
	}
}