package com.recom.domain;

public class Solve {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Solve.solv_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer solvId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Solve.solv_rate_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer solvRateId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Solve.solv_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Integer solvOrdinal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Solve.solv_score
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private Float solvScore;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Solve.solv_answer
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	private String solvAnswer;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Solve.solv_id
	 * @return  the value of Solve.solv_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getSolvId() {
		return solvId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Solve.solv_id
	 * @param solvId  the value for Solve.solv_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setSolvId(Integer solvId) {
		this.solvId = solvId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Solve.solv_rate_id
	 * @return  the value of Solve.solv_rate_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getSolvRateId() {
		return solvRateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Solve.solv_rate_id
	 * @param solvRateId  the value for Solve.solv_rate_id
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setSolvRateId(Integer solvRateId) {
		this.solvRateId = solvRateId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Solve.solv_ordinal
	 * @return  the value of Solve.solv_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Integer getSolvOrdinal() {
		return solvOrdinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Solve.solv_ordinal
	 * @param solvOrdinal  the value for Solve.solv_ordinal
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setSolvOrdinal(Integer solvOrdinal) {
		this.solvOrdinal = solvOrdinal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Solve.solv_score
	 * @return  the value of Solve.solv_score
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public Float getSolvScore() {
		return solvScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Solve.solv_score
	 * @param solvScore  the value for Solve.solv_score
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setSolvScore(Float solvScore) {
		this.solvScore = solvScore;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Solve.solv_answer
	 * @return  the value of Solve.solv_answer
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public String getSolvAnswer() {
		return solvAnswer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Solve.solv_answer
	 * @param solvAnswer  the value for Solve.solv_answer
	 * @mbggenerated  Thu Jul 04 18:29:28 GMT+08:00 2013
	 */
	public void setSolvAnswer(String solvAnswer) {
		this.solvAnswer = solvAnswer;
	}
}