package com.recom.domain;

public class User {
	
	/**	用户类型字段 **/
	public static final int USERTYPE_STUDENT = 1;
	public static final int USERTYPE_TEACHER = 2;
	public static final int USERTYPE_TEACHING_MANAGER = 3;
	public static final int USERTYPE_SYSTEM_MANAGER = 4;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.user_id
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.user_depa_id
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	private Integer userDepaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.user_clas_id
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	private Integer userClasId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.user_loginname
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	private String userLoginname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.user_pwd
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	private String userPwd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.user_realname
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	private String userRealname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.user_gender
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	private String userGender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.user_type
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	private Integer userType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.user_year_of_entrance
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	private String userYearOfEntrance;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.user_cadas_exam_num
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	private String userCadasExamNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.user_id_num
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	private String userIdNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.user_email
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	private String userEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.user_phone_num
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	private String userPhoneNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.user_address
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	private String userAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.user_edu_level
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	private String userEduLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.user_workunit
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	private String userWorkunit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.user_verify
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	private Boolean userVerify;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.user_loginState
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	private Integer userLoginstate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.user_loginNum
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	private Integer userLoginnum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column User.user_remark
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	private String userRemark;

	/**
	 * 用户部门类型
	 * @author lujocom
	 */
	private Integer userDepartType;
	
	/**
	 * 用户头像
	 * @author ZhangXin
	 */
	private Integer userCoverPictureId;

    public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.user_id
	 * @param userId  the value for User.user_id
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.user_depa_id
	 * @return  the value of User.user_depa_id
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public Integer getUserDepaId() {
		return userDepaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.user_depa_id
	 * @param userDepaId  the value for User.user_depa_id
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public void setUserDepaId(Integer userDepaId) {
		this.userDepaId = userDepaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.user_clas_id
	 * @return  the value of User.user_clas_id
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public Integer getUserClasId() {
		return userClasId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.user_clas_id
	 * @param userClasId  the value for User.user_clas_id
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public void setUserClasId(Integer userClasId) {
		this.userClasId = userClasId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.user_loginname
	 * @return  the value of User.user_loginname
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public String getUserLoginname() {
		return userLoginname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.user_loginname
	 * @param userLoginname  the value for User.user_loginname
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public void setUserLoginname(String userLoginname) {
		this.userLoginname = userLoginname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.user_pwd
	 * @return  the value of User.user_pwd
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public String getUserPwd() {
		return userPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.user_pwd
	 * @param userPwd  the value for User.user_pwd
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.user_realname
	 * @return  the value of User.user_realname
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public String getUserRealname() {
		return userRealname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.user_realname
	 * @param userRealname  the value for User.user_realname
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public void setUserRealname(String userRealname) {
		this.userRealname = userRealname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.user_gender
	 * @return  the value of User.user_gender
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public String getUserGender() {
		return userGender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.user_gender
	 * @param userGender  the value for User.user_gender
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public void setUserGender(String userGender) {
		this.userGender = userGender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.user_type
	 * @return  the value of User.user_type
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public Integer getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.user_type
	 * @param userType  the value for User.user_type
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.user_year_of_entrance
	 * @return  the value of User.user_year_of_entrance
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public String getUserYearOfEntrance() {
		return userYearOfEntrance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.user_year_of_entrance
	 * @param userYearOfEntrance  the value for User.user_year_of_entrance
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public void setUserYearOfEntrance(String userYearOfEntrance) {
		this.userYearOfEntrance = userYearOfEntrance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.user_cadas_exam_num
	 * @return  the value of User.user_cadas_exam_num
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public String getUserCadasExamNum() {
		return userCadasExamNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.user_cadas_exam_num
	 * @param userCadasExamNum  the value for User.user_cadas_exam_num
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public void setUserCadasExamNum(String userCadasExamNum) {
		this.userCadasExamNum = userCadasExamNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.user_id_num
	 * @return  the value of User.user_id_num
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public String getUserIdNum() {
		return userIdNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.user_id_num
	 * @param userIdNum  the value for User.user_id_num
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public void setUserIdNum(String userIdNum) {
		this.userIdNum = userIdNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.user_email
	 * @return  the value of User.user_email
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public String getUserEmail() {
		return userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.user_email
	 * @param userEmail  the value for User.user_email
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.user_phone_num
	 * @return  the value of User.user_phone_num
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public String getUserPhoneNum() {
		return userPhoneNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.user_phone_num
	 * @param userPhoneNum  the value for User.user_phone_num
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public void setUserPhoneNum(String userPhoneNum) {
		this.userPhoneNum = userPhoneNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.user_address
	 * @return  the value of User.user_address
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public String getUserAddress() {
		return userAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.user_address
	 * @param userAddress  the value for User.user_address
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.user_edu_level
	 * @return  the value of User.user_edu_level
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public String getUserEduLevel() {
		return userEduLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.user_edu_level
	 * @param userEduLevel  the value for User.user_edu_level
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public void setUserEduLevel(String userEduLevel) {
		this.userEduLevel = userEduLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.user_workunit
	 * @return  the value of User.user_workunit
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public String getUserWorkunit() {
		return userWorkunit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.user_workunit
	 * @param userWorkunit  the value for User.user_workunit
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public void setUserWorkunit(String userWorkunit) {
		this.userWorkunit = userWorkunit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.user_verify
	 * @return  the value of User.user_verify
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public Boolean getUserVerify() {
		return userVerify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.user_verify
	 * @param userVerify  the value for User.user_verify
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public void setUserVerify(Boolean userVerify) {
		this.userVerify = userVerify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.user_loginState
	 * @return  the value of User.user_loginState
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public Integer getUserLoginstate() {
		return userLoginstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.user_loginState
	 * @param userLoginstate  the value for User.user_loginState
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public void setUserLoginstate(Integer userLoginstate) {
		this.userLoginstate = userLoginstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.user_loginNum
	 * @return  the value of User.user_loginNum
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public Integer getUserLoginnum() {
		return userLoginnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.user_loginNum
	 * @param userLoginnum  the value for User.user_loginNum
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public void setUserLoginnum(Integer userLoginnum) {
		this.userLoginnum = userLoginnum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column User.user_remark
	 * @return  the value of User.user_remark
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public String getUserRemark() {
		return userRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column User.user_remark
	 * @param userRemark  the value for User.user_remark
	 * @mbggenerated  Tue Jun 18 19:25:39 GMT+08:00 2013
	 */
	public void setUserRemark(String userRemark) {
		this.userRemark = userRemark;
	}

	public Integer getUserDepartType() {
		return userDepartType;
	}

	public void setUserDepartType(Integer userDepartType) {
		this.userDepartType = userDepartType;
	}

	public Integer getUserCoverPictureId() {
		return userCoverPictureId;
	}

	public void setUserCoverPictureId(Integer userCoverPictureId) {
		this.userCoverPictureId = userCoverPictureId;
	}
	
}